FROM alpine:3.12.6

WORKDIR /usr/src/app
# RUN apk add gcc musl-dev python3-dev libffi-dev openssl-dev 
# Dependencies for cryptography, as azure-identity requires cryptography
RUN apk add gcc musl-dev python3-dev libffi-dev openssl-dev cargo
RUN pip install cryptography==2.1.4
# COPY requirements.txt .
COPY . .
RUN pip install -r requirements.txt

ENTRYPOINT python APIM-Repo-Sync-DEV.py
